### ISSUE TITLE
Weighing User Rating

### ISSUE THREAD

**Issue by ryanding1** [apollo-dw/omdb#7]
As in RYM and other rating services, there is a need to weigh votes based on things like activity and spread of votes in order to preserve the integrity of the rating system. As of now, I believe there to be 3 main issues that need to addressed in the rating system that can be solved each with a weighing function. Each problem has its own reason and a proposed solution that is open for discussion.

_Problem 1._ Users should require a set amount of total votes (100) in order for their vote to be weighted fully. This is to solve the issue of users who join and collude just to vote a certain map a specific rating and never use the service again. 
- I propose a function of weighing 1/(101 - x) where x is the amount of votes from 1-100, and then it stays 1 after that. This is because a linear function has the problem of weights going from 1/100 to 1/50 to 1/33, and this instead will go from 1/100 to 1/99 ... up to 1/1.

_Problem 2._ Users who are inactive for extended periods of time should have their weights reduced. Activity should be required up to a certain extent in order to maintain your influence on the rankings, and so it is only fair that people who do not vote for a long time have their weighing reduced. 
- I propose to use the same function as the name change in osu (but instead of playcount, its based on total ratings), with some factors changed. After that period of time, your profile could be marked with inactive and then your weighing halved.

_Problem 3._ Users whos votes are very unevenly spread should have their weights reduced. This is to prevent people who only vote 0s or 5s from skewing the ranking too much, and will have the same effect as turning their votes into something more like 2.0s and 3.0s. 

- I propose calculating the standard deviation of all a user's votes, and having a linear function based on this where the lower the standard deviation, the less their votes are weighed.

**Comment by apollo-dw** [comment]
generally in agreement with 1 and 3 but not so sure about 2. VINXIS mentioned this earlier but there is a processing overhead that coems with calculating some sort of SD-related function for rating distribution, however I believe this wouldn't become a problem if the chart update interval was large enough (which is bound to be the case) so not an issue IMO

i wonder as well about how these solutions would be implemented with consideration to:
- Bayesian average (used for rankings)
- Average
- Num of ratings for a diff

RYM seems to allow 0-weighted ratings to still count in the number of ratings for a diff - no clue about average.

**Comment by Luminiscental** [comment]
For problem 3, one can scale based on entropy (and it might be sufficient on its own, since low deviation necessitates low entropy)

e.g. (base 2)

100% one rating ⇒ `H = 0` (minimal entropy)
30% one rating, 70% another rating ⇒ `H = -0.3 log2(0.3) - 0.7 log2(0.7) = 0.9...`
50% one rating, 50% another rating ⇒ `H = -0.5 log2(0.5) - 0.5 log2(0.5) = 1.0...`
30%, 30%, 20% ⇒ `H = 1.5...`
10%, 20%, 40%, 20%, 10% ⇒ `H = 2.1...`
10% on every rating ⇒ `H = 3.3...` (maximal entropy; `log2(10)`)

so something linear like `0.1 + H/3.5` might be decent, although it should be checked whether this is overly harsh on reasonable distributions

**Comment by Luminiscental** [comment]
> i wonder as well about how these solutions would be implemented with consideration to:
> 
>   -  Bayesian average (used for rankings)
>   -  Average
>   -  Num of ratings for a diff
> 
> RYM seems to allow 0-weighted ratings to still count in the number of ratings for a diff - no clue about average.

To average with weights replace `sum(value)` with `sum(weight*value)` and replace counts like `n` with `sum(weight)`,
e.g. `sum(weight*value) / sum(weight)` for naïve mean and `[C*m + sum(weight*value)] / [C + sum(weight)]` for Bayesian mean.
That way including 0-weighted values has no impact on the result, since they contribute zero to both sums. For number of ratings I think including 0-weighted ratings is least misleading, and it makes more sense to only discount ratings that get truly deleted for moderation-related reasons or stuff like that.

**Comment by apollo-dw** [comment]
i think we can revisit point 2 in the future if the need arises, however this has now been added as per 2320e070ae9180a28f1dd2db410d1b5dd8a4051f
