### ISSUE TITLE
Allow non-leaderboard maps to appear in OMDB based on petition

### ISSUE THREAD

**Issue by l4ssc** [apollo-dw/omdb#87]
often, great maps like [this one](https://osu.ppy.sh/beatmapsets/904523#osu/1888022) and [this other one](https://osu.ppy.sh/beatmapsets/1100720#osu/2299701) aren't able to be rated because of the (understandable) limitation of OMDB pages to maps that have a leaderboard. with the introduction of descriptor voting, perhaps it'd also be helpful to have non-leaderboard maps able to be included with enough support from community members? :)

**Comment by apollo-dw** [comment]
So things to consider:

- What to do when maps get updated? Reset ratings? These updates could range anywhere between a full remap to metadata changes. Manual checking is not really feasible, because this would requite intimate knowledge of the map before and after the update (too much overhead for too little gain)
- How do we know when maps get updated? Daily script that loops through non-leaderboard OMDB sets?
- There's probably some abuse here that could be done spam-wise that we'd need to somehow prevent. Larger barrier of entry for appearing on charts?

**Comment by l4ssc** [comment]
yeah, i can definitely see the problems that can come from that now. here's my thoughts on these questions:

* when it comes to what to do in the event of map updates, i think that there could be a few ways of going about it. metadata changes and light changes (potentially detectable via a difference of star rating between two versions? i feel like that's decently fair) probably shouldn't reset ratings, but bigger changes/remaps/obviously deletions should. this definitely could be integrated into #84 in order to notify when a map loses its rating so that it's not so annoying when that does happen
* i think a daily script is pretty fair, because i don't imagine rating an unranked/unloved map is necessarily a time-critical thing
* i could definitely see a queue for maps submitted for omdb inclusion

**Comment by totallywaffles** [comment]
Also it could only allow graveyarded maps to lessen the chance of map updates

**Comment by l4ssc** [comment]
amazing, thank you so much!!
